VS2017_INSTALL_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise'
VS2017_LAYOUT_PATH: "{{ROOT_FOR_ANSIBLE_INSTALLS}}\\vs2017layout"

RESHARPER_SETUP_PATH: "{{ROOT_FOR_ANSIBLE_INSTALLS}}\\resharpersetup"
RESHARPER_SETUP_URL: https://download.jetbrains.com/resharper/JetBrains.ReSharperUltimate.2018.1.4.exe
RESHARPER_INSTALLATION_PATH: ""
