---
# this creates layout straight from Microsoft
- name: copy vs2017 installer
  win_copy:
    src: files/vs_enterprise.exe
    dest: "{{ROOT_FOR_ANSIBLE_INSTALLS}}\\vs_enterprise.exe"
    force: no

- name: create layout in layout directory
  win_shell: >
    {{ROOT_FOR_ANSIBLE_INSTALLS}}\vs_enterprise.exe --layout {{VS2017_LAYOUT_PATH}}
    --add Microsoft.VisualStudio.Workload.NetWeb
    --add Component.Github.VisualStudio
    --add Microsoft.VisualStudio.Workload.NetCoreTools
    --add Microsoft.VisualStudio.Workload.Node
    --includeOptional
    --wait
    --quiet
    --lang en-us
