---
- name: check if VS2017 is installed
  win_stat:
    path: "{{ VS2017_INSTALL_PATH }}"
  register: install_path

- include: vs-layout.yml
  when: install_path.stat.exists == false
  tags: try

- name: Install VS2017
  win_shell: >
    {{ VS2017_LAYOUT_PATH }}\vs_enterprise.exe
    --quiet --norestart --wait
  register: install_result
  when: install_path.stat.exists == false
  tags: try

- name: reboot after VS2017 install
  win_reboot:
  when: install_result is changed
  tags: try

- include: resharper.yml
- include: vs-extensions.yml
