---
- include: layout-cache.yml
  when: INSTALL_VS2017_FROM_CACHE
- include: layout-official.yml
  when: not INSTALL_VS2017_FROM_CACHE

- name: Install VS 2017
  win_shell: >
    {{VS2017_LAYOUT_PATH}}\vs_enterprise.exe --quiet --norestart

- include: resharper.yml
