---
# this creates layout straight from Microsoft
- name: copy vs2017 installer
  win_copy:
    src: files/vs_enterprise.exe
    dest: "{{ROOT_FOR_ANSIBLE_INSTALLS}}\\vs_enterprise.exe"
    force: no

- name: create layout in layout directory
  win_shell: >
    {{ROOT_FOR_ANSIBLE_INSTALLS}}\vs_enterprise.exe --layout {{VS2017_LAYOUT_PATH}}
    --add Microsoft.VisualStudio.Workload.NetWeb
    --add Component.Github.VisualStudio
    --add Microsoft.VisualStudio.Workload.NetCoreTools
    --add Microsoft.VisualStudio.Workload.Node
    --add Microsoft.VisualStudio.Workload.NativeDesktop
    --includeOptional
    --wait
    --quiet
    --lang en-us

# Also have to include desktop development components for node-gyp to work:
# Windows 10 SDK (10.0.16299.0) for UWP: C#, VB, JS
# Windows 10 SDK (10.0.16299.0) for UWP: C++
# Windows 10 SDK (10.0.16299.0) for Desktop C++ [x86 and x64]
# Visual Studio C++ core features
# VC++ 2017 v141 toolset (x86,x64)
# -- from:
# https://github.com/nodejs/node-gyp/issues/1278
# and
# https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-enterprise#desktop-development-with-c
