ansible_user: vagrant
ansible_password: vagrant
ansible_port: 5985
ansible_connection: winrm
WinRM self-signed certificates:
ansible_winrm_scheme: http
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
ansible_become_method: runas
ansible_become_user: System
