---

- name: Install useful tools
  win_chocolatey:
    name: '{{ item }}'
    state: present
  with_items:
    - git
    - 7zip
    - python2
    - conemu
    - winmerge


- name: install specific version of node
  win_chocolatey:
    name: nodejs
    version: "8.11.3"
    state: present

- name: install specific version of yarn
  win_chocolatey:
    name: yarn
    state: present
