---

# This fix is to handle:
#    node gyp error, unable to find python2 in path
# This failure occurd when performing "b setup" for the first time

- name: set python in npm config
  win_shell: >
    npm config set python c:\python27\python.exe --global

